M48
; DRILL file {KiCad (6.0.1)} date Mon Jan  9 15:04:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-09T15:04:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.7212Y-2.6324
X2.9488Y-2.6324
T2
X2.5Y-2.5
X2.5Y-6.1614
X6.1614Y-2.5
X6.1614Y-6.1614
T0
M30
